In [105]:
import pandas as pd

In [106]:
from sklearn.datasets import make_regression

In [107]:
x, y = make_regression(n_samples = 100, n_features = 2, n_informative = 2, n_targets = 1, noise = 50)

In [108]:
x

array([[-0.07530535, -1.04449802],
       [-1.51301958, -1.17389242],
       [-0.65678365,  0.13789558],
       [-0.73378004, -0.61665498],
       [-0.01453537, -0.20623739],
       [-0.02942576,  0.47611907],
       [-0.02414409, -0.01675296],
       [ 0.68531149,  0.26790114],
       [-0.40907197, -1.67383526],
       [ 0.15469377, -0.7247455 ],
       [ 0.43251016,  0.01975302],
       [-1.44820896,  2.78096868],
       [ 0.96015074,  0.14891869],
       [ 0.78938262,  0.65369641],
       [-1.50502819,  0.3492976 ],
       [-0.51837901, -0.98469184],
       [-0.58447371,  0.97219736],
       [ 1.4538678 ,  0.25117911],
       [ 0.40267484,  1.62287255],
       [ 1.32511784, -0.70540978],
       [ 2.46411977, -0.26166945],
       [ 0.8236799 ,  1.15294483],
       [ 0.70226514, -0.87569731],
       [-0.26508307,  1.0647524 ],
       [ 0.12680053,  2.7467327 ],
       [ 0.19534307,  1.14064337],
       [ 1.24233662,  0.50053239],
       [ 0.48897453, -0.9190402 ],
       [ 0.0418964 ,

In [109]:
y

array([-149.90787148, -129.45263111,   26.69921795, -105.51996518,
         86.30842032,   24.19017304,    3.26348901,    1.83132711,
       -102.5069625 ,  -37.2351427 ,   67.81662357,  166.57242469,
         70.22615846,   29.67237908,  124.90736384,  -38.95614817,
         78.25526228,   65.60202905,  152.48148399,   -5.28831887,
        -35.97758942,   68.00727488,  -74.23507473,   25.07258236,
        129.29762789,   59.73397057,  -18.60327543,  -18.222613  ,
       -133.42054751,  -27.38401914,  -13.71153036, -110.5382293 ,
        117.85212243,   71.59184544,   33.50592145,   24.10343217,
        -74.37368731,   -0.53441713,  -56.92773734,  -24.90241518,
         59.91020847,   80.61903989,    9.57124053, -156.42866382,
        148.07915714,  -76.37041536,  114.36910559,   58.78806054,
         91.98724387,   53.50734254,   39.80128128,  -45.50111073,
         32.99786741,  -17.96857773,   66.09504172,  -17.52800854,
          0.82595812, -181.98464184,  -58.7938479 ,   48.33016

In [110]:
data = pd.DataFrame({
    "feature1" : x[:, 0],
    "feature2" : x[:, 1],
    "target" : y
})

In [111]:
data.shape

(100, 3)

In [112]:
data

feature1  feature2      target
0  -0.075305 -1.044498 -149.907871
1  -1.513020 -1.173892 -129.452631
2  -0.656784  0.137896   26.699218
3  -0.733780 -0.616655 -105.519965
4  -0.014535 -0.206237   86.308420
..       ...       ...         ...
95 -0.610536  1.163213  118.122862
96 -0.302279  1.061474   65.750387
97 -0.668248  0.089622   14.566757
98 -2.216643 -0.384288  -38.152987
99 -1.708811  1.170851   80.213764

[100 rows x 3 columns]

In [113]:
!pip install plotly

Defaulting to user installation because normal site-packages is not writeable


In [114]:
import plotly.express as ex

In [115]:
fig = ex.scatter_3d(data, x = 'feature1', y = 'feature2', z = 'target')

In [116]:
import plotly.offline as pyo
pyo.init_notebook_mode(connected=True)

In [117]:
fig.show()

In [118]:
from sklearn.model_selection import train_test_split

In [119]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [120]:
x_train.shape

(80, 2)

In [121]:
y_train.shape


(80,)

In [122]:
x_test.shape

(20, 2)

In [123]:
from sklearn.linear_model import LinearRegression

In [124]:
obj = LinearRegression()

In [125]:
obj.fit(x_train, y_train)

LinearRegression()

In [126]:
from sklearn.metrics import r2_score

In [127]:
y_pred = obj.predict(x_test)

In [128]:
r2_score(y_test, y_pred)

0.3121894829034435

In [129]:
# y = m1x1 + m2x2 + b

In [130]:
m = obj.coef_
m

array([ 9.21283693, 66.21315472])

In [132]:
b = obj.intercept_
b

1.9661756305979363

In [137]:
yx = 9.21283693 * (-0.07530535 )+ 66.21315472 * (-1.04449802) + (1.9661756305979363)
yx

-67.8871092819023

In [138]:
x

array([[-0.07530535, -1.04449802],
       [-1.51301958, -1.17389242],
       [-0.65678365,  0.13789558],
       [-0.73378004, -0.61665498],
       [-0.01453537, -0.20623739],
       [-0.02942576,  0.47611907],
       [-0.02414409, -0.01675296],
       [ 0.68531149,  0.26790114],
       [-0.40907197, -1.67383526],
       [ 0.15469377, -0.7247455 ],
       [ 0.43251016,  0.01975302],
       [-1.44820896,  2.78096868],
       [ 0.96015074,  0.14891869],
       [ 0.78938262,  0.65369641],
       [-1.50502819,  0.3492976 ],
       [-0.51837901, -0.98469184],
       [-0.58447371,  0.97219736],
       [ 1.4538678 ,  0.25117911],
       [ 0.40267484,  1.62287255],
       [ 1.32511784, -0.70540978],
       [ 2.46411977, -0.26166945],
       [ 0.8236799 ,  1.15294483],
       [ 0.70226514, -0.87569731],
       [-0.26508307,  1.0647524 ],
       [ 0.12680053,  2.7467327 ],
       [ 0.19534307,  1.14064337],
       [ 1.24233662,  0.50053239],
       [ 0.48897453, -0.9190402 ],
       [ 0.0418964 ,

In [139]:
y

array([-149.90787148, -129.45263111,   26.69921795, -105.51996518,
         86.30842032,   24.19017304,    3.26348901,    1.83132711,
       -102.5069625 ,  -37.2351427 ,   67.81662357,  166.57242469,
         70.22615846,   29.67237908,  124.90736384,  -38.95614817,
         78.25526228,   65.60202905,  152.48148399,   -5.28831887,
        -35.97758942,   68.00727488,  -74.23507473,   25.07258236,
        129.29762789,   59.73397057,  -18.60327543,  -18.222613  ,
       -133.42054751,  -27.38401914,  -13.71153036, -110.5382293 ,
        117.85212243,   71.59184544,   33.50592145,   24.10343217,
        -74.37368731,   -0.53441713,  -56.92773734,  -24.90241518,
         59.91020847,   80.61903989,    9.57124053, -156.42866382,
        148.07915714,  -76.37041536,  114.36910559,   58.78806054,
         91.98724387,   53.50734254,   39.80128128,  -45.50111073,
         32.99786741,  -17.96857773,   66.09504172,  -17.52800854,
          0.82595812, -181.98464184,  -58.7938479 ,   48.33016

In [142]:
import plotly.graph_objects as go


import numpy as np

x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)

xGrid, yGrid = np.meshgrid(y, x)
final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

z_final = obj.predict(final).reshape(10,10)

z = z_final

fig = ex.scatter_3d(data, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()