In [ ]:
lst = [1, "str", 1.8, "iwuq"]

Numpy => 



In [1]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable
DEPRECATION: distro-info 1.1build1 has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
DEPRECATION: python-debian 0.1.43ubuntu1 has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of python-debian or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [2]:
import numpy as np

In [ ]:
# ndarray = objects created in numpy with the help of array()

In [3]:
a = np.array(23)


In [5]:
print(a.ndim)

0


In [6]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [7]:
print(arr.ndim)

1


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [10]:
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [11]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
print(arr1.ndim)

3


In [14]:
arr2 = np.array([1, 2, 3, 4], ndmin = 5)

In [16]:
print(arr2.ndim)

5


In [ ]:
# index

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [21]:
print(arr[1, 2])

6


In [22]:
arr[1, 2] + arr[0, 2]

9

In [23]:
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [27]:
# print(arr1[1,1,0])
print(arr1[0, 1, 1])

5


In [ ]:
# Slicing:

In [31]:
# [start:end:step]
ar1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(ar1[1 : 7 : 2])

[2 4 6]


In [33]:
arr = np.array([[1, 2, 3, 23, 45], [4, 5, 6, 98, 67]])
print(arr[1, 1 : 4])

[ 5  6 98]


In [1]:
import numpy as np

In [2]:
arr = np.array([12, 23, 34, 10])

In [7]:
# a = ("10.1")
# print(type(a))

<class 'tuple'>


In [8]:
arr.dtype

dtype('int64')

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
arr.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [11]:
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr1)
arr1.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [13]:
# shape

arr = np.array([1, 2,3 ,4, 5,6,7,8, 9, 10])

print(arr.ndim)

1


In [16]:
# reshape()
# 4, 2
newarr = arr.reshape(5, 2)
newarr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
ittreation
arr = np.array([1, 2,3 ,4, 5,6,7,8, 9, 10])

total = 0
for i in arr:
    total = total + i
print(total)

55


In [20]:
arr = np.array([[1, 2, 3, 23, 45], [4, 5, 6, 98, 67]])

for i in arr:
    print(i)
    for y in i:
        print(y)

[ 1  2  3 23 45]
1
2
3
23
45
[ 4  5  6 98 67]
4
5
6
98
67


In [23]:
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in arr1:
    for y in i:
        for z in y:
            print(z)
    

1
2
3
4
5
6
7
8
9
10
11
12


In [25]:
# Joining Numpy array
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [27]:
c = a + b
c

array([ 6,  8, 10, 12])

In [30]:
arr3 = np.concatenate((a, b))
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

# Joing array using stack

arr4 = np.stack((a, b))


In [37]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.array([9, 10, 11, 12])

arr4 = np.stack((a, b, c))
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
# Splitting numpy array

arr = np.array([1, 2, 6,3 ,4, 5,6,7,8,6,  9, 10])
newar = np.array_split(arr, 4)

# where()
ser = np.where(arr == 6)
ser

(array([2, 6, 9]),)

In [41]:
newar

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]

In [50]:
# sort
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  6,  6,  7,  8,  9, 10])

In [52]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
c = np.array([[9, 10, 11, 12], [5, 6, 7, 8]])

arr4 = np.stack((a, c))
arr4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 5,  6,  7,  8]]])